/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsResult {
  'registrationsPerEvent' : Array<RegistrationsPerEvent>,
  'registrationsPerCategory' : Array<RegistrationsPerCategory>,
  'averageRatingsByEvent' : Array<AverageRatingByEvent>,
  'registrationsPerMonth' : Array<RegistrationsPerMonth>,
}
export interface AverageRatingByEvent {
  'eventId' : EventId,
  'averageRating' : number,
  'totalFeedback' : bigint,
  'eventName' : string,
}
export interface CreateEventRequest {
  'date' : string,
  'name' : string,
  'time' : string,
  'description' : string,
  'category' : EventCategory,
  'capacity' : bigint,
  'department' : string,
  'location' : string,
}
export interface Event {
  'id' : EventId,
  'date' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'time' : string,
  'description' : string,
  'category' : EventCategory,
  'capacity' : bigint,
  'department' : string,
  'location' : string,
  'registrationCount' : bigint,
}
export type EventCategory = { 'social' : null } |
  { 'other' : null } |
  { 'academic' : null } |
  { 'cultural' : null } |
  { 'technical' : null } |
  { 'sports' : null };
export type EventId = bigint;
export interface Feedback {
  'id' : FeedbackId,
  'eventId' : EventId,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'comment' : string,
  'rating' : bigint,
}
export type FeedbackId = bigint;
export interface Registration {
  'id' : RegistrationId,
  'status' : RegistrationStatus,
  'eventId' : EventId,
  'userId' : UserId,
  'registrationDate' : Timestamp,
}
export type RegistrationId = bigint;
export type RegistrationStatus = { 'cancelled' : null } |
  { 'registered' : null };
export interface RegistrationsPerCategory {
  'count' : bigint,
  'category' : string,
}
export interface RegistrationsPerEvent {
  'eventId' : EventId,
  'count' : bigint,
  'eventName' : string,
}
export interface RegistrationsPerMonth { 'month' : string, 'count' : bigint }
export type Timestamp = bigint;
export interface UpdateEventRequest {
  'id' : EventId,
  'date' : string,
  'name' : string,
  'time' : string,
  'description' : string,
  'category' : EventCategory,
  'capacity' : bigint,
  'department' : string,
  'location' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelRegistration' : ActorMethod<[RegistrationId], boolean>,
  'createEvent' : ActorMethod<[CreateEventRequest], Event>,
  'deleteEvent' : ActorMethod<[EventId], boolean>,
  'deleteFeedback' : ActorMethod<[FeedbackId], boolean>,
  'getAnalytics' : ActorMethod<[], AnalyticsResult>,
  'getAverageRating' : ActorMethod<[], Array<AverageRatingByEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEvent' : ActorMethod<[EventId], [] | [Event]>,
  'getFeedbackByUser' : ActorMethod<[], Array<Feedback>>,
  'getFeedbackForEvent' : ActorMethod<[EventId], Array<Feedback>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getRegistration' : ActorMethod<[RegistrationId], [] | [Registration]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listRegistrations' : ActorMethod<[], Array<Registration>>,
  'listRegistrationsByEvent' : ActorMethod<[EventId], Array<Registration>>,
  'listRegistrationsByUser' : ActorMethod<[], Array<Registration>>,
  'listUsers' : ActorMethod<[], Array<[UserId, UserProfile]>>,
  'registerForEvent' : ActorMethod<[EventId], Registration>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedback' : ActorMethod<[EventId, bigint, string], Feedback>,
  'updateEvent' : ActorMethod<[UpdateEventRequest], boolean>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];