/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RegistrationId = IDL.Nat;
export const EventCategory = IDL.Variant({
  'social' : IDL.Null,
  'other' : IDL.Null,
  'academic' : IDL.Null,
  'cultural' : IDL.Null,
  'technical' : IDL.Null,
  'sports' : IDL.Null,
});
export const CreateEventRequest = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : EventCategory,
  'capacity' : IDL.Nat,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const EventId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Event = IDL.Record({
  'id' : EventId,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : EventCategory,
  'capacity' : IDL.Nat,
  'department' : IDL.Text,
  'location' : IDL.Text,
  'registrationCount' : IDL.Nat,
});
export const FeedbackId = IDL.Nat;
export const RegistrationsPerEvent = IDL.Record({
  'eventId' : EventId,
  'count' : IDL.Nat,
  'eventName' : IDL.Text,
});
export const RegistrationsPerCategory = IDL.Record({
  'count' : IDL.Nat,
  'category' : IDL.Text,
});
export const AverageRatingByEvent = IDL.Record({
  'eventId' : EventId,
  'averageRating' : IDL.Float64,
  'totalFeedback' : IDL.Nat,
  'eventName' : IDL.Text,
});
export const RegistrationsPerMonth = IDL.Record({
  'month' : IDL.Text,
  'count' : IDL.Nat,
});
export const AnalyticsResult = IDL.Record({
  'registrationsPerEvent' : IDL.Vec(RegistrationsPerEvent),
  'registrationsPerCategory' : IDL.Vec(RegistrationsPerCategory),
  'averageRatingsByEvent' : IDL.Vec(AverageRatingByEvent),
  'registrationsPerMonth' : IDL.Vec(RegistrationsPerMonth),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Feedback = IDL.Record({
  'id' : FeedbackId,
  'eventId' : EventId,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const RegistrationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'registered' : IDL.Null,
});
export const Registration = IDL.Record({
  'id' : RegistrationId,
  'status' : RegistrationStatus,
  'eventId' : EventId,
  'userId' : UserId,
  'registrationDate' : Timestamp,
});
export const UpdateEventRequest = IDL.Record({
  'id' : EventId,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : EventCategory,
  'capacity' : IDL.Nat,
  'department' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelRegistration' : IDL.Func([RegistrationId], [IDL.Bool], []),
  'createEvent' : IDL.Func([CreateEventRequest], [Event], []),
  'deleteEvent' : IDL.Func([EventId], [IDL.Bool], []),
  'deleteFeedback' : IDL.Func([FeedbackId], [IDL.Bool], []),
  'getAnalytics' : IDL.Func([], [AnalyticsResult], ['query']),
  'getAverageRating' : IDL.Func([], [IDL.Vec(AverageRatingByEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
  'getFeedbackByUser' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getFeedbackForEvent' : IDL.Func([EventId], [IDL.Vec(Feedback)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getRegistration' : IDL.Func(
      [RegistrationId],
      [IDL.Opt(Registration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'listRegistrationsByEvent' : IDL.Func(
      [EventId],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'listRegistrationsByUser' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
      ['query'],
    ),
  'registerForEvent' : IDL.Func([EventId], [Registration], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func([EventId, IDL.Nat, IDL.Text], [Feedback], []),
  'updateEvent' : IDL.Func([UpdateEventRequest], [IDL.Bool], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RegistrationId = IDL.Nat;
  const EventCategory = IDL.Variant({
    'social' : IDL.Null,
    'other' : IDL.Null,
    'academic' : IDL.Null,
    'cultural' : IDL.Null,
    'technical' : IDL.Null,
    'sports' : IDL.Null,
  });
  const CreateEventRequest = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : EventCategory,
    'capacity' : IDL.Nat,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const EventId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Event = IDL.Record({
    'id' : EventId,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : EventCategory,
    'capacity' : IDL.Nat,
    'department' : IDL.Text,
    'location' : IDL.Text,
    'registrationCount' : IDL.Nat,
  });
  const FeedbackId = IDL.Nat;
  const RegistrationsPerEvent = IDL.Record({
    'eventId' : EventId,
    'count' : IDL.Nat,
    'eventName' : IDL.Text,
  });
  const RegistrationsPerCategory = IDL.Record({
    'count' : IDL.Nat,
    'category' : IDL.Text,
  });
  const AverageRatingByEvent = IDL.Record({
    'eventId' : EventId,
    'averageRating' : IDL.Float64,
    'totalFeedback' : IDL.Nat,
    'eventName' : IDL.Text,
  });
  const RegistrationsPerMonth = IDL.Record({
    'month' : IDL.Text,
    'count' : IDL.Nat,
  });
  const AnalyticsResult = IDL.Record({
    'registrationsPerEvent' : IDL.Vec(RegistrationsPerEvent),
    'registrationsPerCategory' : IDL.Vec(RegistrationsPerCategory),
    'averageRatingsByEvent' : IDL.Vec(AverageRatingByEvent),
    'registrationsPerMonth' : IDL.Vec(RegistrationsPerMonth),
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'eventId' : EventId,
    'userId' : UserId,
    'submittedAt' : Timestamp,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const RegistrationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'registered' : IDL.Null,
  });
  const Registration = IDL.Record({
    'id' : RegistrationId,
    'status' : RegistrationStatus,
    'eventId' : EventId,
    'userId' : UserId,
    'registrationDate' : Timestamp,
  });
  const UpdateEventRequest = IDL.Record({
    'id' : EventId,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : EventCategory,
    'capacity' : IDL.Nat,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelRegistration' : IDL.Func([RegistrationId], [IDL.Bool], []),
    'createEvent' : IDL.Func([CreateEventRequest], [Event], []),
    'deleteEvent' : IDL.Func([EventId], [IDL.Bool], []),
    'deleteFeedback' : IDL.Func([FeedbackId], [IDL.Bool], []),
    'getAnalytics' : IDL.Func([], [AnalyticsResult], ['query']),
    'getAverageRating' : IDL.Func(
        [],
        [IDL.Vec(AverageRatingByEvent)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
    'getFeedbackByUser' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getFeedbackForEvent' : IDL.Func([EventId], [IDL.Vec(Feedback)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getRegistration' : IDL.Func(
        [RegistrationId],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'listRegistrationsByEvent' : IDL.Func(
        [EventId],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'listRegistrationsByUser' : IDL.Func(
        [],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
        ['query'],
      ),
    'registerForEvent' : IDL.Func([EventId], [Registration], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func([EventId, IDL.Nat, IDL.Text], [Feedback], []),
    'updateEvent' : IDL.Func([UpdateEventRequest], [IDL.Bool], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };