/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type EventId = bigint;
export interface Registration {
    id: RegistrationId;
    status: RegistrationStatus;
    eventId: EventId;
    userId: UserId;
    registrationDate: Timestamp;
}
export interface Feedback {
    id: FeedbackId;
    eventId: EventId;
    userId: UserId;
    submittedAt: Timestamp;
    comment: string;
    rating: bigint;
}
export type RegistrationId = bigint;
export interface UpdateEventRequest {
    id: EventId;
    date: string;
    name: string;
    time: string;
    description: string;
    category: EventCategory;
    capacity: bigint;
    department: string;
    location: string;
}
export interface Event {
    id: EventId;
    date: string;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    time: string;
    description: string;
    category: EventCategory;
    capacity: bigint;
    department: string;
    location: string;
    registrationCount: bigint;
}
export interface AnalyticsResult {
    registrationsPerEvent: Array<RegistrationsPerEvent>;
    registrationsPerCategory: Array<RegistrationsPerCategory>;
    averageRatingsByEvent: Array<AverageRatingByEvent>;
    registrationsPerMonth: Array<RegistrationsPerMonth>;
}
export interface RegistrationsPerCategory {
    count: bigint;
    category: string;
}
export type UserId = Principal;
export interface RegistrationsPerEvent {
    eventId: EventId;
    count: bigint;
    eventName: string;
}
export interface RegistrationsPerMonth {
    month: string;
    count: bigint;
}
export interface CreateEventRequest {
    date: string;
    name: string;
    time: string;
    description: string;
    category: EventCategory;
    capacity: bigint;
    department: string;
    location: string;
}
export type FeedbackId = bigint;
export interface AverageRatingByEvent {
    eventId: EventId;
    averageRating: number;
    totalFeedback: bigint;
    eventName: string;
}
export interface UserProfile {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export enum EventCategory {
    social = "social",
    other = "other",
    academic = "academic",
    cultural = "cultural",
    technical = "technical",
    sports = "sports"
}
export enum RegistrationStatus {
    cancelled = "cancelled",
    registered = "registered"
}
export enum UserRole {
    admin = "admin",
    student = "student"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelRegistration(registrationId: RegistrationId): Promise<boolean>;
    createEvent(req: CreateEventRequest): Promise<Event>;
    deleteEvent(eventId: EventId): Promise<boolean>;
    deleteFeedback(feedbackId: FeedbackId): Promise<boolean>;
    getAnalytics(): Promise<AnalyticsResult>;
    getAverageRating(): Promise<Array<AverageRatingByEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getEvent(eventId: EventId): Promise<Event | null>;
    getFeedbackByUser(): Promise<Array<Feedback>>;
    getFeedbackForEvent(eventId: EventId): Promise<Array<Feedback>>;
    getProfile(user: Principal): Promise<UserProfile | null>;
    getRegistration(registrationId: RegistrationId): Promise<Registration | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllFeedback(): Promise<Array<Feedback>>;
    listEvents(): Promise<Array<Event>>;
    listRegistrations(): Promise<Array<Registration>>;
    listRegistrationsByEvent(eventId: EventId): Promise<Array<Registration>>;
    listRegistrationsByUser(): Promise<Array<Registration>>;
    listUsers(): Promise<Array<[UserId, UserProfile]>>;
    registerForEvent(eventId: EventId): Promise<Registration>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitFeedback(eventId: EventId, rating: bigint, comment: string): Promise<Feedback>;
    updateEvent(req: UpdateEventRequest): Promise<boolean>;
    updateProfile(profile: UserProfile): Promise<void>;
}
import type { CreateEventRequest as _CreateEventRequest, Event as _Event, EventCategory as _EventCategory, EventId as _EventId, Registration as _Registration, RegistrationId as _RegistrationId, RegistrationStatus as _RegistrationStatus, Timestamp as _Timestamp, UpdateEventRequest as _UpdateEventRequest, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelRegistration(arg0: RegistrationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRegistration(arg0);
            return result;
        }
    }
    async createEvent(arg0: CreateEventRequest): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_CreateEventRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Event_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_CreateEventRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Event_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteEvent(arg0: EventId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteFeedback(arg0: FeedbackId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedback(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getAverageRating(): Promise<Array<AverageRatingByEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: EventId): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackByUser(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackByUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackByUser();
            return result;
        }
    }
    async getFeedbackForEvent(arg0: EventId): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackForEvent(arg0);
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistration(arg0: RegistrationId): Promise<Registration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistration(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistration(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllFeedback();
            return result;
        }
    }
    async listEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRegistrations(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegistrations();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegistrations();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRegistrationsByEvent(arg0: EventId): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegistrationsByEvent(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegistrationsByEvent(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRegistrationsByUser(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegistrationsByUser();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegistrationsByUser();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<[UserId, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerForEvent(arg0: EventId): Promise<Registration> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForEvent(arg0);
                return from_candid_Registration_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForEvent(arg0);
            return from_candid_Registration_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFeedback(arg0: EventId, arg1: bigint, arg2: string): Promise<Feedback> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async updateEvent(arg0: UpdateEventRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(to_candid_UpdateEventRequest_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(to_candid_UpdateEventRequest_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_EventCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventCategory): EventCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationStatus): RegistrationStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Registration_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Registration): Registration {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Registration]): Registration | null {
    return value.length === 0 ? null : from_candid_Registration_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RegistrationId;
    status: _RegistrationStatus;
    eventId: _EventId;
    userId: _UserId;
    registrationDate: _Timestamp;
}): {
    id: RegistrationId;
    status: RegistrationStatus;
    eventId: EventId;
    userId: UserId;
    registrationDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_RegistrationStatus_n22(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        userId: value.userId,
        registrationDate: value.registrationDate
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EventId;
    date: string;
    name: string;
    createdAt: _Timestamp;
    createdBy: _UserId;
    time: string;
    description: string;
    category: _EventCategory;
    capacity: bigint;
    department: string;
    location: string;
    registrationCount: bigint;
}): {
    id: EventId;
    date: string;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    time: string;
    description: string;
    category: EventCategory;
    capacity: bigint;
    department: string;
    location: string;
    registrationCount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        time: value.time,
        description: value.description,
        category: from_candid_EventCategory_n9(_uploadFile, _downloadFile, value.category),
        capacity: value.capacity,
        department: value.department,
        location: value.location,
        registrationCount: value.registrationCount
    };
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _UserProfile]): [UserId, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    other: null;
} | {
    academic: null;
} | {
    cultural: null;
} | {
    technical: null;
} | {
    sports: null;
}): EventCategory {
    return "social" in value ? EventCategory.social : "other" in value ? EventCategory.other : "academic" in value ? EventCategory.academic : "cultural" in value ? EventCategory.cultural : "technical" in value ? EventCategory.technical : "sports" in value ? EventCategory.sports : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "student" in value ? UserRole.student : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    registered: null;
}): RegistrationStatus {
    return "cancelled" in value ? RegistrationStatus.cancelled : "registered" in value ? RegistrationStatus.registered : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Registration>): Array<Registration> {
    return value.map((x)=>from_candid_Registration_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _UserProfile]>): Array<[UserId, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function to_candid_CreateEventRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEventRequest): _CreateEventRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_EventCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): _EventCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateEventRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateEventRequest): _UpdateEventRequest {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}): {
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n30(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EventId;
    date: string;
    name: string;
    time: string;
    description: string;
    category: EventCategory;
    capacity: bigint;
    department: string;
    location: string;
}): {
    id: _EventId;
    date: string;
    name: string;
    time: string;
    description: string;
    category: _EventCategory;
    capacity: bigint;
    department: string;
    location: string;
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        time: value.time,
        description: value.description,
        category: to_candid_EventCategory_n5(_uploadFile, _downloadFile, value.category),
        capacity: value.capacity,
        department: value.department,
        location: value.location
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    name: string;
    time: string;
    description: string;
    category: EventCategory;
    capacity: bigint;
    department: string;
    location: string;
}): {
    date: string;
    name: string;
    time: string;
    description: string;
    category: _EventCategory;
    capacity: bigint;
    department: string;
    location: string;
} {
    return {
        date: value.date,
        name: value.name,
        time: value.time,
        description: value.description,
        category: to_candid_EventCategory_n5(_uploadFile, _downloadFile, value.category),
        capacity: value.capacity,
        department: value.department,
        location: value.location
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    student: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): {
    social: null;
} | {
    other: null;
} | {
    academic: null;
} | {
    cultural: null;
} | {
    technical: null;
} | {
    sports: null;
} {
    return value == EventCategory.social ? {
        social: null
    } : value == EventCategory.other ? {
        other: null
    } : value == EventCategory.academic ? {
        academic: null
    } : value == EventCategory.cultural ? {
        cultural: null
    } : value == EventCategory.technical ? {
        technical: null
    } : value == EventCategory.sports ? {
        sports: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
